export const authConstants = {
  //register
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  //login
  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",

  //singout
  SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAILURE: "SIGNOUT_FAILURE",
};

export const userConstants = {
  //get user
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILURE: "GET_USER_FAILURE",

  //delete user
  DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILURE: "DELETE_USER_FAILURE",
};

export const cartConstatnts = {
  //add to cart
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",

  //delete to cart
  DELETE_CART_REQUEST: "DELETE_CART_REQUEST",
  DELETE_CART_SUCCESS: "DELETE_CART_SUCCESS",
  DELETE_CART_FAILURE: "DELETE_CART_FAILURE",
};

export const orderConstants = {
  //Add order
  PLACE_ORDER_REQUEST: "PLACE_ORDER_REQUEST",
  PLACE_ORDER_SUCCESS: "PLACE_ORDER_SUCCESS",
  PLACE_ORDER_FAILURE: "PLACE_ORDER_FAILURE",

  //get user orders
  GET_USER_ORDER_REQUEST: "GET_USER_ORDER_REQUEST",
  GET_USER_ORDER_SUCCESS: "GET_USER_ORDER_SUCCESS",
  GET_USER_ORDER_FAILURE: "GET_USER_ORDER_FAILURE",

  //get all orders
  GET_ALL_ORDER_REQUEST: "GET_ALL_ORDER_REQUEST",
  GET_ALL_ORDER_SUCCESS: "GET_ALL_ORDER_SUCCESS",
  GET_ALL_ORDER_FAILURE: "GET_ALL_ORDER_FAILURE",

  //deliver orders
  DELIVER_ORDER_REQUEST: "DELIVER_ORDER_REQUEST",
  DELIVER_ORDER_SUCCESS: "DELIVER_ORDER_SUCCESS",
  DELIVER_ORDER_FAILURE: "DELIVER_ORDER_FAILURE",
};

export const pizzaConstants = {
  //add pizza
  ADD_PIZZA_REQUEST: "ADD_PIZZA_REQUEST",
  ADD_PIZZA_SUCCESS: "ADD_PIZZA_SUCCESS",
  ADD_PIZZA_FAILURE: "ADD_PIZZA_FAILURE",

  //get all pizzas
  GET_ALL_PIZZA_REQUEST: "GET_ALL_PIZZA_REQUEST",
  GET_ALL_PIZZA_SUCCESS: "GET_ALL_PIZZA_SUCCESS",
  GET_ALL_PIZZA_FAILURE: "GET_ALL_PIZZA_FAILURE",

  //get pizza by id
  GET_PIZZABYID_REQUEST: "GET_PIZZABYID_REQUEST",
  GET_PIZZABYID_SUCCESS: "GET_PIZZABYID_SUCCESS",
  GET_PIZZABYID_FAILURE: "GET_PIZZABYID_FAILURE",

  //update pizza
  UPDATE_PIZZA_REQUEST: "UPDATE_PIZZA_REQUEST",
  UPDATE_PIZZA_SUCCESS: "UPDATE_PIZZA_SUCCESS",
  UPDATE_PIZZA_FAILURE: "UPDATE_PIZZA_FAILURE",

  //delete pizza
  DELETE_PIZZA_REQUEST: "DELETE_PIZZA_REQUEST",
  DELETE_PIZZA_SUCCESS: "DELETE_PIZZA_SUCCESS",
  DELETE_PIZZA_FAILURE: "DELETE_PIZZA_FAILURE",
};
